### ISSUE TITLE
CI repo no longer at that URL

### ISSUE THREAD

**Issue by Fireant456** [jesperbagge/unturned#4]
The link https://ci.rocketmod.net/job/Rocket.Unturned/lastSuccessfulBuild/artifact/Rocket.Unturned/bin/Release in the build script is no longer being hosted. Is there an alternative that can be updated to revitalize this repo.

**Comment by jesperbagge** [comment]
Hi. The original developer and maintainer of RocketMod has archived his project and removed all infrastructure. It seems that Smartly Dressed Games has [forked the code](https://github.com/SmartlyDressedGames/Legally-Distinct-Missile) but necessary folders and install scripts seems to be missing. I'm sorry that I don't have the time and interest to maintain my own repo.
